channels:
  - conda-forge
dependencies:
  - asbl-py
  - ca-certificates
  - certifi
  - conda-merge
  - hide_code
  - ipykernel
  - ipywidgets
  - jupyter_contrib_nbextensions
  - jupytext
  - notebook=6.5.4
  - openssl
  - python=3.10
  - ruamel.yaml
