channels:
  - nvidia/label/cuda-11.8.0
  - nvidia
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - ca-certificates
  - certifi
  - compilers
  - cuda
  - faiss-gpu
  - gcc==11.4
  - glib
  - ipykernel
  - ipywidgets
  - libaio
  - nbformat
  - ninja
  - openssl
  - pip
  - py-cpuinfo
  - pynvim
  - pysnooper
  - python=3.10
  - pytorch
  - pytorch-cuda=11.8
  - sysroot_linux-64==2.17
  - torchaudio
  - torchvision
